{"uuid":"7bf7d0c8-2451-43c2-a8d8-7a4b34f62270","historyId":"1ca2809ad8fe4ca7e592033fff4ab00","fullName":"com.source.classes.requisitions.create.CreateTest.create","labels":[{"name":"package","value":"com.source.classes.requisitions.create.CreateTest"},{"name":"testClass","value":"com.source.classes.requisitions.create.CreateTest"},{"name":"testMethod","value":"create"},{"name":"parentSuite","value":"GePS-HOPES_YEA PS Catalog Test Cases"},{"name":"suite","value":"Requisition Create"},{"name":"subSuite","value":"com.source.classes.requisitions.create.CreateTest"},{"name":"host","value":"Issac"},{"name":"thread","value":"29476@Issac.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"epic","value":"Requisitions"},{"name":"feature","value":"Requisition Create"},{"name":"severity","value":"normal"}],"links":[],"name":"Requisition Create Test","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Requisition Create was not Successful expected [0] but found [200]","trace":"java.lang.AssertionError: Requisition Create was not Successful expected [0] but found [200]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1419)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1383)\r\n\tat com.source.classes.requisitions.create.CreateTest.create(CreateTest.java:21)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1269)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Test Description: Verify Requester Can Create The Requisition","steps":[],"attachments":[],"parameters":[{"name":"type","value":"PS"},{"name":"purchaseType","value":"Catalog"}],"start":1747024519604,"stop":1747024608878}